name: Minimal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_ENV: test

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create required directories
      run: mkdir -p data
    
    - name: Run tests
      run: |
        echo "Running unit tests..."
        npm run test:unit
        
        echo "Running integration tests..."
        npm run test:integration
        
        echo "Running frontend tests..."
        npm run test:frontend
    
    - name: Test server and E2E
      run: |
        echo "Starting server..."
        npm start &
        SERVER_PID=$!
        
        echo "Waiting for server..."
        sleep 10
        
        echo "Testing health endpoint..."
        curl -f http://localhost:3000/health
        
        echo "Running E2E tests..."
        npm run test:e2e
        
        echo "Stopping server..."
        kill $SERVER_PID || true
    
    - name: Security check (non-blocking)
      run: |
        echo "Running security audit..."
        npm audit --audit-level=high || echo "Security issues found - please review"
      continue-on-error: true