name: Simple CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Quick Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Run all tests
      run: npm test
    
    - name: Test server startup
      run: |
        npm start &
        sleep 5
        curl -f http://localhost:3000/health || echo "Health check failed"
        pkill -f "node server.js" || true